name: Build the project

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Run build with Gradle Wrapper
      run: ./gradlew build --scan

    - name: Check
      run: ls -lh ./build/libs

    - name: Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/1037093614604/locations/global/workloadIdentityPools/github-connection-plus-default/providers/github-connection-plus-provider'
        service_account: 'mira-builder-103@mira-392912.iam.gserviceaccount.com'
    
    - name: Deploy
      run: ./gradlew appengineDeploy