name: Deploy the project

on:
    push:
        branches:
            - 'main'

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'
        
        steps:
            - id: 'auth'
              uses: 'google-github-actions/auth@v1'
              with:
                workload_identity_provider: 'projects/1037093614604/locations/global/workloadIdentityPools/github-connection-plus-default/providers/github-connection-plus-provider'
                service_account: 'mira-builder-103@mira-392912.iam.gserviceaccount.com'
            
            - id: 'deploy'
              uses: 'google-github-actions/deploy-appengine@v1'
              with:
                project_id: 'mira-392912'
                deliverables: './src/main/appengine/app.yaml'
